#!/bin/bash
set -e

git clone https://github.com/certbot/certbot.git --branch ${SOURCE_BRANCH} --single-branch --depth 1 ../core/certbot
docker build -f ../core/Dockerfile -t certbot/certbot:${DOCKER_TAG} ../core

mv ../core/certbot ./
